# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180330_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='memory',
            field=models.CharField(max_length=50, verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mode',
            field=models.CharField(max_length=50, verbose_name='\u670d\u52a1\u5668\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='service',
            name='os_version',
            field=models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='service',
            name='postion',
            field=models.CharField(max_length=50, verbose_name='\u670d\u52a1\u5668\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ps',
            field=models.TextField(max_length=1024, verbose_name='\u5907\u6ce8\u6d88\u606f'),
        ),
    ]
