# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180330_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False, verbose_name='\u670d\u52a1\u5668\u72b6\u6001'),
        ),
    ]
