# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pushPath',
            new_name='pushMessage',
        ),
        migrations.AddField(
            model_name='project',
            name='RocllgitVersion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56de\u6eda\u7248\u672c'),
        ),
    ]
