# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180410_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='RocllgitVersion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pushMessage',
        ),
    ]
