# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180411_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='RocllgitVersion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56de\u6eda\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='project',
            name='pushMessage',
            field=models.CharField(default='sa@sunteng.com', max_length=120, verbose_name='\u63a8\u9001\u901a\u77e5'),
        ),
    ]
