# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180411_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='changeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectChangeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
