# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180411_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='myapp.Status'),
        ),
    ]
