# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180411_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='postServer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postServer', to='myapp.Service'),
        ),
    ]
