# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180411_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dstServerKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Key'),
        ),
    ]
