# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180425_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='\u8fdb\u5ea6\u6761'),
        ),
    ]
