# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20180425_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('gitversion', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('servers', models.TextField()),
                ('repertory', models.CharField(max_length=128)),
                ('before_secretkey', models.TextField()),
                ('before_server', models.CharField(max_length=128)),
                ('before_port', models.IntegerField(max_length=11)),
                ('before_user', models.CharField(max_length=128)),
                ('before_script', models.CharField(max_length=128)),
                ('before_config', models.TextField()),
                ('before_include', models.TextField()),
                ('channel_secretkey', models.TextField()),
                ('channel_server', models.CharField(max_length=128)),
                ('channel_port', models.IntegerField(max_length=11)),
                ('channel_user', models.CharField(max_length=128)),
                ('after_secretkey', models.TextField()),
                ('after_user', models.CharField(max_length=128)),
                ('after_port', models.IntegerField(max_length=11)),
                ('after_script', models.CharField(max_length=128)),
                ('before_scriptbody', models.TextField()),
                ('target_path', models.CharField(max_length=128)),
                ('push_path', models.CharField(max_length=128)),
                ('after_fileuser', models.CharField(max_length=128)),
                ('exclude', models.TextField()),
                ('status', models.IntegerField(max_length=10)),
                ('result', models.TextField()),
                ('note', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modifytime', models.DateTimeField(auto_now=True, verbose_name='\u5199\u5165\u65f6\u95f4')),
            ],
        ),
    ]
