# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_oldtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtask',
            name='after_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oldtask',
            name='before_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oldtask',
            name='channel_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oldtask',
            name='status',
            field=models.IntegerField(),
        ),
    ]
